# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dysx' do
  # Comment the next line if you don't want to use dynamic frameworks

  use_frameworks!

  # Pods for dysx
  
  pod 'AFNetworking', '~> 4.0.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  # pod 'AMap3DMap-NO-IDFA'
  pod 'AMapLocation-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'


  target 'dysxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dysxUITests' do
    # Pods for testing
  end

end

